preserve exit status with wrapped errors
containerd/go-runc pull request #68
Opened 2020-10-16 18:11 UTC by coryb

We need to be able capture the exit status from `Exec`, currently the status is discarded.  This PR uses wrapped error to preserve the status via an `ExitError`.  

I have also removed the Go `1.12.x` travis testing, since `errors.As` used in the test was introduced in `1.13`.

cc @tonistiigi

2020-10-16 19:05 UTC, tonistiigi approved these changes
@crosbymichael @AkihiroSuda

2020-10-16 20:11 UTC, estesp approved these changes
LGTM

2020-10-17 04:32 UTC, AkihiroSuda requested changes
Looks good but a single nit

2020-10-17 04:32 UTC, AkihiroSuda commented on console_test.go
> +	defer os.Setenv("XDG_RUNTIME_DIR", "")
Let's getenv the initial value

2020-10-17 05:39 UTC, coryb commented on console_test.go
> +	defer os.Setenv("XDG_RUNTIME_DIR", "")
Updated

2020-10-17 06:05 UTC, AkihiroSuda approved these changes

2020-10-17 06:05 UTC, merged